test

diff --git a/.github/workflows/api.yml b/.github/workflows/api.yml
--- a/.github/workflows/api.yml
+++ b/.github/workflows/api.yml
@@ -9,46 +9,46 @@ on:
   workflow_dispatch:
 
 jobs:
-  build-and-push-image:
-    # if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
-    runs-on: [ubuntu-latest]
-    permissions:
-      contents: read
-      packages: write
-    steps:
-      - uses: actions/checkout@v2
+  # build-and-push-image:
+  #   # if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
+  #   runs-on: [ubuntu-latest]
+  #   permissions:
+  #     contents: read
+  #     packages: write
+  #   steps:
+  #     - uses: actions/checkout@v2
 
-      - name: Login to GitHub Docker Registry
-        uses: docker/login-action@v1
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Login to GitHub Docker Registry
+  #       uses: docker/login-action@v1
+  #       with:
+  #         registry: ghcr.io
+  #         username: ${{ github.actor }}
+  #         password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Get STAGE
-        id: get_stage
-        run: |
-          if [[ $BASE_REF == "master" || $REF == "refs/heads/master" ]]
-          then
-              echo "::set-output name=STAGE::prod"
-          elif [[ $BASE_REF == "dev" || $REF == "refs/heads/dev" ]]
-          then
-              echo "::set-output name=STAGE::dev"
-          else
-              echo "Invalid branch" && exit 1
-          fi
-        env:
-          REF: ${{ github.ref }}
-          BASE_REF: ${{ github.base_ref }}
+  #     - name: Get STAGE
+  #       id: get_stage
+  #       run: |
+  #         if [[ $BASE_REF == "master" || $REF == "refs/heads/master" ]]
+  #         then
+  #             echo "::set-output name=STAGE::prod"
+  #         elif [[ $BASE_REF == "dev" || $REF == "refs/heads/dev" ]]
+  #         then
+  #             echo "::set-output name=STAGE::dev"
+  #         else
+  #             echo "Invalid branch" && exit 1
+  #         fi
+  #       env:
+  #         REF: ${{ github.ref }}
+  #         BASE_REF: ${{ github.base_ref }}
 
-      - name: Build container image
-        uses: docker/build-push-action@v2
-        with:
-          context: api
-          push: true
-          tags: |
-            ghcr.io/${{ github.repository }}/${{ env.PROJECT }}:${{ github.sha }}
-            ghcr.io/${{ github.repository }}/${{ env.PROJECT }}:${{ steps.get_stage.outputs.STAGE }}
+  #     - name: Build container image
+  #       uses: docker/build-push-action@v2
+  #       with:
+  #         context: api
+  #         push: true
+  #         tags: |
+  #           ghcr.io/${{ github.repository }}/${{ env.PROJECT }}:${{ github.sha }}
+  #           ghcr.io/${{ github.repository }}/${{ env.PROJECT }}:${{ steps.get_stage.outputs.STAGE }}
 
   deploy:
     # if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
